<?php

return [
    [
        'key'  => 'ladyfauzia',
        'name' => 'Lady Fauzia Co.',
        'sort' => 10,
    ],
    [
        'key'  => 'ladyfauzia.loyalty',
        'name' => 'Joy Points Loyalty Settings',
        'info' => 'Configure points earning rates and rewards',
        'icon' => 'settings/store.svg',
        'sort' => 1,
    ],
    [
        'key'    => 'ladyfauzia.loyalty.points',
        'name'   => 'Earning Rules',
        'info'   => 'Set points rewards for customer actions',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'earn_rate',
                'title'         => 'Points Per Dollar Spent',
                'type'          => 'text',
                'validation'    => 'required|numeric|min:0',
                'default'       => '1',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'signup_points',
                'title'         => 'Account Creation Points',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '100',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'review_points',
                'title'         => 'Approved Product Review Points',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '50',
                'channel_based' => false,
                'locale_based'  => false,
            ],
        ],
    ],
    [
        'key'  => 'ladyfauzia.vip',
        'name' => 'VIP Membership Settings',
        'info' => 'Configure VIP tier spend thresholds',
        'icon' => 'settings/store.svg',
        'sort' => 2,
    ],
    [
        'key'    => 'ladyfauzia.vip.thresholds',
        'name'   => 'Spend Thresholds',
        'info'   => 'Set cumulative spending thresholds (USD) for VIP levels',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'silver_spend',
                'title'         => 'Silver Tier Threshold ($)',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '500',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'gold_spend',
                'title'         => 'Gold Tier Threshold ($)',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '1500',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'elite_spend',
                'title'         => 'Elite Tier Threshold ($)',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '3000',
                'channel_based' => false,
                'locale_based'  => false,
            ],
        ],
    ],
    [
        'key'  => 'ladyfauzia.referral',
        'name' => 'Referral Settings',
        'info' => 'Configure referral rewards and rules',
        'icon' => 'settings/store.svg',
        'sort' => 3,
    ],
    [
        'key'    => 'ladyfauzia.referral.points',
        'name'   => 'Referral Rewards',
        'info'   => 'Set points rewards for referrers and referred friends',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'referrer_reward',
                'title'         => 'Points Reward to Referrer',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '200',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'referred_reward',
                'title'         => 'Points Reward to Referred Friend',
                'type'          => 'text',
                'validation'    => 'required|integer|min:0',
                'default'       => '100',
                'channel_based' => false,
                'locale_based'  => false,
            ],
        ],
    ],
];
